### ISSUE TITLE
Please make examples folder

### ISSUE THREAD

**Issue by casainho** [greatest-gatsby/fruity_menu#1]
I am new to coding and Pyhton and I struggle to get this menu working.

I have the menu being shown on my sh1106, but I wounder how I can setup something for select a menu entry.

Thank you for this library.

**Comment by greatest-gatsby** [comment]
Sure I can add some examples. Do you want to share what you have or are trying to achieve?

**Comment by greatest-gatsby** [comment]
@casainho I have also pushed a decent update from my personal GitLab to here, see if any of that helps.

**Comment by casainho** [comment]
I am trying to achieve this kind of menus - note that I can see a label and value of each menu entry / editable, also edit it right away:

![image](https://user-images.githubusercontent.com/147128/211554072-88267896-bca6-4814-b728-f61d0ebb8f56.png)

![image](https://user-images.githubusercontent.com/147128/211554129-ac9fba5f-7636-4d45-a90f-74c01110bf99.png)

[More info](https://endless-sphere.com/forums/viewtopic.php?f=7&t=113971).

That firmware were developed in C by other developer, but now I am trying to switch to CircuitPython.

[Here is the configurations for each editable](https://github.com/OpenSourceEBike/EV_Display_Bluetooth_Ant/blob/59e13cea8828411007f3b13808c97efb2b7aaa6b/firmware/display/configscreen.c), that I wish your library could also implement:

![image](https://user-images.githubusercontent.com/147128/211555788-80e8b64f-7028-40e6-87c5-62a01dce6fc9.png)

**Comment by greatest-gatsby** [comment]
Ah I see. Out of sheer simplicity I kept the value-setting separate from the display of the options, but I will take a look and see how I can rearrange them to show both at once.

**Comment by casainho** [comment]
> Ah I see. Out of sheer simplicity I kept the value-setting separate from the display of the options, but I will take a look and see how I can rearrange them to show both at once.

It is important for user to see the value as he navigates the menu / list of variables, see here the same library being used on a big display:

https://youtu.be/QKonmtvztwY?t=147

And by the way, my display is simple as this:

![image](https://user-images.githubusercontent.com/147128/211558128-1687e1fc-7377-4aa2-b8ab-3f291f03793f.png)

![image](https://user-images.githubusercontent.com/147128/211558233-c98154c8-a3f1-4719-bf88-13cfc5320a62.png)

And this is the very simple schematic (but I am using now ESP32-S2 instead of NRF52840, because then I can program it wireless):

![image](https://user-images.githubusercontent.com/147128/211558466-b41840c1-294f-4fc0-9aa2-706f3d400def.png)

**Comment by greatest-gatsby** [comment]
Very nice, very clean. I will see what I can do re: display value in menu, and also add some examples.

**Comment by casainho** [comment]
And to be clear, I got this with your library:

https://user-images.githubusercontent.com/147128/211571354-52272122-a4de-4972-9a53-a7cb546cea91.mp4

And please note that my display is rotate: display.rotation = 270
Seems the menus are not perfect when using the rotation.

Here is the code I did and where I hope to implement the display firmware using CircuitPython and your fruity_menu library:
[fruity_menu](https://github.com/OpenSourceEBike/EV_Display_Bluetooth_Ant/blob/CircuitPython-VESC/firmware/main.py)

> @casainho I have also pushed a decent update from my personal GitLab to here, see if any of that helps.

Hmmm, the last commit I see is from months ago.

**Comment by greatest-gatsby** [comment]
Yeah I haven't worked on this library in about a year, but the GitHub repo was several commits behind my personal GitLab repo.

**Comment by casainho** [comment]
I think it is useful for the kind of displays I use and systems that always has a good number of configurations. I did search for CircuitPyhton and I only found this library, so I think there is a good potential for it.

This are the 3 things in order, that I think I wish could be improved for newcomers as me:
1. Have some pictures or small video from a real display showing some examples of menus
2. Make clear it is expected to work with any board and display that runs CircuitPyhton (but it was tested on xx version of CircuitPyhton and on the specific board)
3. Have examples folder

**Comment by greatest-gatsby** [comment]
Thank you for these suggestions! And thanks for your vote of confidence!

**Comment by joshmarinacci** [comment]
Would it be okay if I submitted a PR with doc improvements and pictures?

**Comment by greatest-gatsby** [comment]
Please do! I got sidetracked when I went to take pictures. I am merging the readme changes I had already made but there are no pictures in it.

**Comment by greatest-gatsby** [comment]
@joshmarinacci I added some pics and a handful of doc improvements, but I will still eagerly accept more if you still want to contribute more.
