### ISSUE TITLE
String list data type

### ISSUE THREAD

**Issue by medienverbinder** [greatest-gatsby/fruity_menu#2]
@greatest-gatsby Thank you very much for this project!

I have successfully tried the menu on a raspberry pi pico w with a ssd1306 oled display and a rotary encoder and it works great.

Do you have a solution or an idea for another data type in the form of a list? In addition to the already existing data types (integer, float and boolean), a selection could be made via a passed (string) list.

About like this (for example language settings):

<img src="https://user-images.githubusercontent.com/4519686/233601827-2efc9ee6-3ba4-4b19-946f-19de833ea2c3.gif" width="300" height="220">

Thank you!

**Comment by furbrain** [comment]
I've also recently been playing with this and a "choices" menu could be really good. I think I can code that up pretty easily. @greatest-gatsby are you happy for me to submit a PR?

**Comment by greatest-gatsby** [comment]
Sorry all, I lost control of my old email domain so I wasn't getting email notifications. I am looking into this now, including looking at @furbrain 's PR (thank you for your contribution btw!)

**Comment by greatest-gatsby** [comment]
I like this feature request, I will take some time over the next few days to get this implemented.

**Comment by furbrain** [comment]
Hi there, I actually implemented this in my repo - have a look!

Phil

**Comment by greatest-gatsby** [comment]
Wow, I merged that PR without even recognizing that part. Shows how rusty my knowledge is with this repo. 🤓 

Thank you for your contributions!

**Comment by greatest-gatsby** [comment]
Closing this PR thanks to @furbrain 's contribution. Feel free to reopen this or another issue if it didn't quite meet your needs.
