### ISSUE TITLE
Menu Doesn't Refresh On Scroll or Click

### ISSUE THREAD

**Issue by thompsonline** [greatest-gatsby/fruity_menu#4]
My understanding is that the menu should update or refresh when the scroll or click methods are called. The only way I can get it to refresh is by calling show_menu().

menu = Menu(board.display, title='Main Menu', height=240, width=240)
menu.add_action_button('Start', action=startGame)
menu.add_value_button('Setting 1', board.setting1, on_value_set=updateSetting1, min_val=3, max_val=12)
menu.add_value_button('Setting 2', board.setting2, on_value_set=updateSetting2, min_val=15, max_val=300, scroll_factor=15)
menu.show_menu()

keys = keypad.Keys((board.upPin, board.dnPin, board.selectPin), value_when_pressed=False, pull=True)

while True:
    event = keys.events.get()
    if event:
        key_number = event.key_number
        if event.pressed:
            if key_number == 0:
                menu.scroll(-1)
            elif key_number == 1:
                menu.scroll(1)
            elif key_number == 2:
                menu.click()

        # Without this, the menu doesn't change when the buttons are pressed.
        # With this, the menu updates but all the resources are re-created with each event 
        menu.show_menu()   

Is there a different way to update the menu without recreating all the resources or redrawing the whole thing?

**Comment by imdbere** [comment]
Same here, can't really get it to work at all

**Comment by greatest-gatsby** [comment]
Sorry all, I lost control of my old email domain so I wasn't getting email notifications. I am looking into this issue now.

**Comment by greatest-gatsby** [comment]
I was mistaken in my README when I said it auto-redraws. It most definitely did not auto redraw for `scroll(delta)`. I have updated it so that it does indeed auto-redraw by scrolling; this can be disabled by invoking it as `scroll(delta, False)`. I am creating a new release now.

Added in [b69be2b](https://github.com/greatest-gatsby/fruity_menu/commit/b69be2bf05a94b6b16876672843761a162e0350e)

**Comment by greatest-gatsby** [comment]
Created v1.2.0 release with this bug fixed: https://pypi.org/project/fruity-display-menu/1.2.0/

Closing this ticket now. Thanks for the bug report, sorry for the delay in addressing it.
